[project]
name = "kverus"
version = "0.1.0"
description = "Scalable and Resilient Formal Verification Proof Generation for Rust Code"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.2",
    "parse>=1.20.2",
    "tiktoken>=0.8.0",
    "promex-verus",
]

[dependency-groups]
dev = ["requests>=2.32.4", "deptry>=0.23.1", "pre-commit>=4.3.0"]

[tool.uv]
index-url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"

[tool.uv.workspace]
members = ["processor/promex-verus"]

[tool.uv.sources]
promex-verus = { workspace = true }
